[CS_Hud]
Credits1="GT INTERACTIVE"
; EN: Credits2="LEGEND ENTERTAINMENT"
Credits2="LEGENDA ROZRYWKA"
; EN: Credits3="AND EPIC GAMES"
Credits3="I EPICKIE GRY"
; EN: Credits4="PRESENT"
Credits4="TERAŹNIEJSZOŚĆ"
GameTitle="UNREAL: RETURN TO NA PALI"
